name: lackeyccg
base: core18
version: '0.1a0'
summary: LackeyCCG is a computer program used to play collectible card games.
description: |
  LackeyCCG is a computer program used to play virtually any collectible card
  game (CCG) against online opponents or for building and testing of CCG decks
  offline in a solitaire mode[1]. It also allows for the searching of cards
  within each CCG. LackeyCCG currently has both Mac and Windows versions and
  will soon have a Linux version. The program was created by Trevor Agnitti and
  is currently in its beta testing stage.

grade: devel
confinement: strict

architectures:
  - build-on: amd64

environment:
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  WINEDLLOVERRIDES: "mshtml=" # prevent Wine Mono and Wine Gecko pop-ups
  # TRICKS: "winxp corefonts mfc40"
  # VIRTDESKTOP: 1
  # WINEARCH: "win32"
  MONO_URL: "https://dl.winehq.org/wine/wine-mono/4.7.1/wine-mono-4.7.1.msi"
  LC_ALL: "C.UTF-8"
  SNAP_SOMMELIER_STRICT: "1" # exit when unset variables are used

apps:
  lackeyccg:
    extensions:
      - gnome-3-28
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "LackeyCCG/LackeyCCG.exe"
    plugs:
      - home
      - network
      - network-bind
  wine:
    extensions:
      - gnome-3-28
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions:
      - gnome-3-28
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  lackeyccg-zip:
    plugin: dump
    source-type: local
    source: ./snap/local/LackeyCCG
  sommelier-cncra:
    plugin: dump
    source: ./snap/local/scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-runtime
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
    organize:
      'sommelier': bin/

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
